Project/ITSSelfRunning/Models/Run/ActivityRunner.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITSSelfRunning.Models.Run
{
    public class ActivityRunner
    {
        public int IdActivity { get; set; }
        public int IdRunner { get; set; }
        public int Type { get; set; }
        public string UriGara { get; set; }
    }
}

Project/ITSSelfRunning/Models/Run/SelfieTime.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITSSelfRunning.Models.Run
{
    public class SelfieTime
    {
        public string Photo { get; set; }
        public DateTime Time { get; set; }
        public int IdActivity { get; set; }
    }
}

Project/ITSSelfRunning/Controllers/RunController.cs
using Dapper;
using ITSSelfRunning.Models;
using ITSSelfRunning.Models.Run;
using ITSSelfRunning.Models.RunViewModels;
using Lib.Repos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.EventHubs;
using Microsoft.Extensions.Configuration;
using Microsoft.WindowsAzure.Storage.Blob;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using ITSSelfRunning.Services;
using Lib;
using Lib.Repos.Interfaces;
using Activity = Lib.Activity;
using Point = Lib.Point;

namespace ITSSelfRunning.Controllers
{
    public class RunController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IActivityRepo _activityRepo;
        private readonly IEventHubService _eventHubService;
        private readonly IPointRepo _pointRepo;
        private readonly IRunnerRepo _runnerRepo;
        private readonly ICloudStorageService _cloudStorageService;
        private readonly ISharedRunService _sharedRunService;




        public RunController(UserManager<ApplicationUser> userManager,
                                IActivityRepo activityRepo, IEventHubService eventHubService,
                                IPointRepo pointRepo, IRunnerRepo runnerRepo, ICloudStorageService cloudStorageService,
                                ISharedRunService sharedRunService)
        {
            _userManager = userManager;
            _activityRepo = activityRepo;
            _eventHubService = eventHubService;
            _pointRepo = pointRepo;
            _runnerRepo = runnerRepo;
            _cloudStorageService = cloudStorageService;
            _sharedRunService = sharedRunService;
        }




        /// <summary>
        /// View list with all runner's activities
        /// </summary>
        /// <returns>the view list</returns>
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var runner = await _runnerRepo.GetUserAsync(_userManager.GetUserId(User));
            // ViewData["ProfilePhotoUri"] = runner.PhotoUri;
            IEnumerable<Activity> list = await _activityRepo.GetTrainingsAsync(runner.Id);
            return View(list);
        }



        /// <summary>
        /// Starts the training
        /// </summary>
        /// <param name="activityId">the id of the activity to start</param>
        /// <param name="isToOpen">checks if the activity is not already open</param>
        /// <returns>the view with the running activity</returns>
        [Authorize]
        public async Task<IActionResult> RunTraining(int activityId, int activityType, string uriGara, bool isToOpen)
        {
            var runner = await _runnerRepo.GetUserAsync(_userManager.GetUserId(User));
            if (isToOpen)
            {
                await _activityRepo.OpenTrainingAsync(activityId);
            }

            return View(new ActivityRunner
            {
                IdRunner = runner.Id,
                IdActivity = activityId,
                Type = activityType,
                UriGara = uriGara
            });
        }


        /// <summary>
        /// Returns the view with the data of a closed training
        /// </summary>
        /// <param name="act">the closed activity to analyze</param>
        /// <returns>Returns the view with the data of a closed training</returns>
        [Authorize]
        public async Task<IActionResult> ViewTrainingData(Activity act)
        {
            IEnumerable<Point> list = await _pointRepo.GetActivityPointsAsync(act.Id);
            ViewData["Telemetry"] = list;
            ViewData["Activity"] = act;
            list.AsList().RemoveAt(0);
            return View();
        }

        /// <summary>
        /// Close a training
        /// </summary>
        /// <param name="activityId">the id of the activity to close</param>
        /// <returns>redirect to Index View</returns>
        [Authorize]
        public async Task<IActionResult> EndTraining(int activityId)
        {
            await _activityRepo.CloseTrainingAsync(activityId);
            return RedirectToAction("Index");
        }


        /// <summary>
        /// Returns view to create a training
        /// </summary>
        /// <returns> Returns view to create a training</returns>
        [HttpGet]
        [Authorize]
        public IActionResult CreateTraining()
        {
            return View();
        }




        /// <summary>
        /// Create a training
        /// </summary>
        /// <param name="activity">User submitted parameters</param>
        /// <returns>Index view</returns>
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreateTraining(ActivityViewModel activity)
        {
            var runner = await _runnerRepo.GetUserAsync(_userManager.GetUserId(User));
            Activity obj = new Activity
            {
                IdRunner = runner.Id,
                Name = activity.Name,
                Place = activity.Place,
                Type = 1, //1= training, 2 = gara
            };
            await _activityRepo.InsertAsync(obj);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Sends the telemetry point to eventHub
        /// </summary>
        /// <param name="point">the given point from the client</param>
        /// <returns>Status code 200</returns>
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> SendPoint([FromBody] Point point)
        {

            var msg = JsonConvert.SerializeObject(new
            {
                Type = "Point",
                Msg = JsonConvert.SerializeObject(point)
            });
            await _eventHubService.SendMsg(msg);
            return Json(new { result = "ok" });
        }

        /// <summary>
        /// Returns view summary of activity to start
        /// </summary>
        /// <param name="activity"></param>
        /// <returns>View with the activity to start</returns>
        [Authorize]
        public IActionResult StartTraining(Activity activity)
        {
            return View(activity);
        }

        /// <summary>
        /// Uploads to Azure Blob a given photo as b64 string and sends uri and time taken to eventHub
        /// </summary>
        /// <param name="photo">string Photo = b64 img, DateTime Time = time taken</param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public async Task UploadSelfie([FromBody] SelfieTime photo)
        {
            var blobUri = await _cloudStorageService.UploadPhotoFromB64(photo.Photo);
            var msg = JsonConvert.SerializeObject(new
            {
                Type = "Selfie",
                Msg = JsonConvert.SerializeObject(new
                {
                    SelfieUri = blobUri,
                    Time = photo.Time,
                    IdActivity = photo.IdActivity
                })
            });
            await _eventHubService.SendMsg(msg);

        }







        /// <summary>
        /// Returns the view of all the races in SharedRuns WebApp
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> GetRaceList()
        {
            return View(await _sharedRunService.GetAllRaces());
        }


        /// <summary>
        /// View of the details of a race
        /// </summary>
        /// <param name="uriGara">identifier of the race</param>
        /// <returns></returns>
        public async Task<IActionResult> RaceDetails(string uriGara)
        {
            return View(await _sharedRunService.GetRaceDetails(uriGara));
        }

        /// <summary>
        /// Registers the current user to a race on SharedRuns and creates the current istance-activity
        /// </summary>
        /// <param name="race">the race to join</param>
        /// <returns></returns>
        public async Task<IActionResult> JoinRace(Race race)
        {
            var runner = await _runnerRepo.GetUserAsync(_userManager.GetUserId(User));
            await _sharedRunService.JoinRace(race.UriGara, runner.Id);

            Activity personalRace = new Activity
            {
                IdRunner = runner.Id,
                Name = race.Name,
                Place = race.Place,
                UriGara = race.UriGara,
                Type = 2,
                CreationDate = DateTime.Now,
                Status = 0
            };

            await _activityRepo.InsertAsync(personalRace);

            return RedirectToAction("Index");
        }

    }
}

Project/ITSSelfRunning/Views/Run/ActivityData.cshtml
@model Lib.Activity
@{
    ViewData["Title"] = "ActivityData";
}

<h2><b>Your training:</b> @Model.Name</h2>
<div><b>At:</b> @Model.Place</div>

Project/ITSSelfRunning/Views/Run/CreateTraining.cshtml
@model ITSSelfRunning.Models.RunViewModels.ActivityViewModel

@{
    ViewData["Title"] = "CreateTraining";
}

<h2>CreateTraining</h2>
<hr />
<div class="row">
    <div class="col-md-4">

        <form asp-action="CreateTraining">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Place" class="control-label"></label>
                <input asp-for="Place" id="place" class="form-control" />
                <span asp-validation-for="Place" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAh4cgxhziWIt6rEa5XFffeOmEBmMIEesA" async defer></script>
<script src="~/js/location.js"></script>


<script type="text/javascript">
    var place = document.getElementById("place");

    getPlace(function(address) {
        place.value = address;
    });
</script>

Project/ITSSelfRunning/Views/Run/GetRaceList.cshtml
@model IEnumerable<Lib.Race>

@{
    ViewData["Title"] = "GetRaceList";
}

<h2>GetRaceList</h2>

<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Place)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreationDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UriGara)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Place)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UriGara)
            </td>
            <td>
                @Html.ActionLink("Details", "RaceDetails", new {  uriGara=item.UriGara})
            </td>
        </tr>
}
    </tbody>
</table>

Project/ITSSelfRunning/Views/Run/Index.cshtml
@model IEnumerable<Lib.Activity>

@{
    ViewData["Title"] = "Index";

}


<style>
    body {
        margin-top: 10vh;
    }

    .trainings {
        padding-top: 10vh;
    }

    .races {
        padding-top: 10vh;
    }
</style>




<div class="row">
    <div class="col-lg-2">
        <a asp-controller="Run" asp-action="CreateTraining" class="btn btn-primary" id="createTraining">
            Create new Training
        </a>
    </div>
    <div class="col-lg-2">
        <a asp-controller="Run" asp-action="GetRaceList" class="btn btn-primary" id="joinRaces">Join a race</a>
    </div>
</div>
<br />
<table class="table" id="trainingTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Place)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody></tbody>
</table>



<table class="table" id="raceTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Place)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UriGara)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

<!--
<button id="previous" onclick="previousPage()"><<</button>
<p id="currentPage"></p>
<button id="next" onclick="nextPage()">>></button>-->




<script>
    var pageNumRace = 1;
    var itemsPerPageRace = 10;
    var counterRace = 0;
    var pageNumTraining = 1;
    var itemsPerPageTraining = 10;
    var counterTraining = 0;
    var tableRace = document.getElementById("raceTable");
    var tableTraining = document.getElementById("trainingTable");
    compileTables();

    function compileTables() {



        @foreach (var item in Model)
    {
        if (item.Type == 1)
        {

            <text>
                counterTraining++;
                if (counterTraining > itemsPerPageTraining * (pageNumTraining - 1) &&
                    counterTraining <= itemsPerPageTraining * pageNumTraining) {
                    var row = tableTraining.insertRow(1);

                    var nameRow = row.insertCell(0);
                    nameRow.innerHTML = "@item.Name";

                    var creationDate = row.insertCell(1);
                    creationDate.innerHTML = "@item.CreationDate";

                    var place = row.insertCell(2);
                    place.innerHTML = "@item.Place";

                    var rowStatus = row.insertCell(3);
                    var button = row.insertCell(4);
                    if (@item.Status === 0) {
                        rowStatus.innerHTML = '<img src="images/start.png" width="40" height="40"/>';
                        button.innerHTML =
                            '@Html.ActionLink("Start", "StartTraining", item, new {@class = "btn btn-primary btnGriglia"})';
                    } else if (@item.Status === 1) {
                        rowStatus.innerHTML = '<img src="images/open.png" width="40" height="40"/>';
                        button.innerHTML =
                            '@Html.ActionLink("View", "RunTraining", new {activityId = item.Id, isToOpen = false, activityType = item.Type}, new {@class = "btn btn-primary btnGriglia"})';
                    } else if (@item.Status === 2) {
                        rowStatus.innerHTML = '<img src="images/closed.png" width="40" height="40"/>';
                        button.innerHTML =
                            '@Html.ActionLink("Show data", "ViewTrainingData", item, new {@class = "btn btn-primary btnGriglia"})';
                    }
                }
            </text>
        }
        else if (item.Type == 2)
        {



            <text>
                    counterRace++;
                    if (counterRace > itemsPerPageRace * (pageNumRace - 1) &&
                        counterRace <= itemsPerPageRace * pageNumRace) {
                        var row = tableRace.insertRow(1);


                        var nameRow = row.insertCell(0);
                        nameRow.innerHTML = "@item.Name";

                        var creationDate = row.insertCell(1);
                        creationDate.innerHTML = "@item.CreationDate";

                        var place = row.insertCell(2);
                        place.innerHTML = "@item.Place";

                        var rowStatus = row.insertCell(3);


                        var uriRace = row.insertCell(4);
                        uriRace.innerHTML = "@item.UriGara";
                        var button = row.insertCell(5);
                        if (@item.Status === 0) {
                            rowStatus.innerHTML = '<img src="images/start.png" width="40" height="40"/>';
                            button.innerHTML =
                                '@Html.ActionLink("Start", "StartTraining", item, new {@class = "btn btn-primary btnGriglia"})';
                        } else if (@item.Status === 1) {
                            rowStatus.innerHTML = '<img src="images/open.png" width="40" height="40"/>';
                            button.innerHTML =
                                '@Html.ActionLink("View", "RunTraining", new {activityId = item.Id, isToOpen = false, activityType = item.Type, uriGara = item.UriGara}, new {@class = "btn btn-primary btnGriglia"})';
                        } else if (@item.Status === 2) {
                            rowStatus.innerHTML = '<img src="images/closed.png" width="40" height="40"/>';
                            button.innerHTML =
                                '@Html.ActionLink("Show data", "ViewTrainingData", item, new {@class = "btn btn-primary btnGriglia"})';
                        }
                    }
                </text>

    }
    }
    }



    /*
    function previousPage() {
        $("#trainingTable tbody .tableTrainingRows").remove();
       // pageNumRace = pageNumRace + 1;
        pageNumTraining = pageNumTraining + 1;
        //compileTables();
    }*/
</script>

Project/ITSSelfRunning/Views/Run/PointData.cshtml
@model IEnumerable<Lib.Point>
@{
    ViewData["Title"] = "PointData";
}
<style>
    #map {
        height: 400px; /* The height is 400 pixels */
        width: 100%; /* The width is the width of the web page */
    }
</style>
@{ var totalTime = Model.Last().Time.Subtract(Model.First().Time);}


<div id="totalTime"><b>Total Time:</b> @totalTime.Days Days - @totalTime.Hours Hours - @totalTime.Minutes Minutes - @totalTime.Seconds Seconds - @totalTime.Milliseconds Milliseconds</div>
<div id="startTime"><b>Start Time:</b> @Model.First().Time</div>
<div id="endTime"><b>End Time:</b> @Model.Last().Time</div>
<div id="map"></div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script type="text/javascript">
    var route = [];
    var lenght = @Model.Count();
    var totalTimeDiv = document.getElementById('totalTime');
    var startTimeDiv = document.getElementById('startTime');
    var endTimeDiv = document.getElementById('endTime');

    var map = new google.maps.Map(document.getElementById('map'), {
        center: { lat: @Model.First().Latitude.ToString().Replace(",", "."), lng: @Model.First().Longitude.ToString().Replace(",", ".") },
        zoom: 15
    });


    @foreach (var r in Model)
    {
        var x = @r.Latitude.ToString().Replace(",", ".");
        var y = @r.Longitude.ToString().Replace(",", ".");

        <text>
            route.push({ lat: @x, lng: @y });
        </text>
                if (r.UriSelfie != null)
                {
                    <text>
                        var marker = new google.maps.Marker({
                            position: { lat: @x, lng: @y },
                            map: map,
                            icon: {
                                size: new google.maps.Size(220, 220),
                                scaledSize: new google.maps.Size(60, 50),
                                origin: new google.maps.Point(0, 0),
                                anchor: new google.maps.Point(16, 16),
                                url: "@r.UriSelfie"
                            }
                        });
                    </text>
                }
     }



    var flightPath = new google.maps.Polyline({
        path: route,
        geodesic: true,
        strokeColor: '#f44242',
        strokeOpacity: 1.0,
        strokeWeight: 3
    });
    flightPath.setMap(map);





    

</script>

Project/ITSSelfRunning/Views/Run/RaceDetails.cshtml
@model Lib.Race

@{
    ViewData["Title"] = "RaceDetails";
}

<h2>RaceDetails</h2>

<div>
    <h4>Race</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Place)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Place)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UriGara)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UriGara)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Join", "JoinRace", @Model) |
    <a asp-action="Index">Back to List</a>
</div>

Project/ITSSelfRunning/Views/Run/RunTraining.cshtml
@model ITSSelfRunning.Models.Run.ActivityRunner

@{
    ViewData["Title"] = "RunTraining";
}

<style>
    #map {
        height: 400px; /* The height is 400 pixels */
        width: 100%; /* The width is the width of the web page */
    }

    .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }
    .modal-content {
        background-color: #ffffff;
        margin: 15% auto; /* 15% from the top and centered */
        padding: 20px;
        border: 1px solid #888;
        width: 50%; /* Could be more or less, depending on screen size */
    }
    .close {
        color: #000000;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }



    .modalButtonBar {
        padding-top: 3vh;
        padding-left: 3vh;
    }


    .modal-content {
        padding-left: 3vh;
    }


    #my_camera {
        float: left;
    }

    #results {
        float: right;
    }


</style>

<body>
<div id="modale" class="modal">
    <div class="modal-content">
        <div class="row"><span class="close">&times;</span></div>
        

        <div class="row">
            <div id="my_camera"></div>
            <div id="results"></div>
        </div>

        <form>
            <div class="row modalButtonBar">
                <input type=button value="Take Selfie" onClick="take_snapshot()" class="btn btn-primary">
                <input type=button value="Upload Selfie" onClick="uploadSelfie()" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>



<h2>RunTraining</h2>
<button class = "btn btn-primary" id="openModal">Take a selfie</button>
@Html.ActionLink("End", "EndTraining", new { activityId = @Model.IdActivity }, new { @class = "btn btn-primary" })


<div id="map"></div>
<div id="data"></div>
    



<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAh4cgxhziWIt6rEa5XFffeOmEBmMIEesA"></script>
<script src="~/js/location.js"></script>
<script src="~/js/webcam.min.js"></script>


<script type="text/javascript">
    var data = document.getElementById("data");

    getLocation(@Model.IdActivity, @Model.IdRunner, @Model.Type, "@Model.UriGara");

    function take_snapshot() {
        Webcam.snap(function(data_uri) {
            document.getElementById('results').innerHTML =
                '<img id="selfie" src="' + data_uri + '"/>';
        });
    }


    function uploadSelfie() {
        var photo = document.getElementById("selfie").src;
        var data = JSON.stringify({
            "photo": photo,
            "time": new Date().toISOString(),
            "idActivity" : @Model.IdActivity
        });

        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(createSelfieMarker, showError);
          
        }
        
        $.ajax({
            type: "POST",
            url: "/Run/UploadSelfie",
            data: data,
            dataType: "json",
            headers: {
                'Content-Type': 'application/json'
            }
        });
    }



    function createSelfieMarker(position) {


        var marker = new google.maps.Marker({
            position: { lat: position.coords.latitude, lng: position.coords.longitude },
            map: map,
            icon: {
                size: new google.maps.Size(220,220),
                scaledSize: new google.maps.Size(60,50),
                origin: new google.maps.Point(0,0),
                url: document.getElementById("selfie").src,
                anchor: new google.maps.Point(16,16)}
        });
    }


    var modal = document.getElementById('modale');
    var openModal = document.getElementById("openModal");
    var close = document.getElementsByClassName("close")[0];

    openModal.onclick = function() {
        modal.style.display = "block";
        Webcam.set({
            width: 320,
            height: 240,
            image_format: 'jpeg',
            jpeg_quality: 90
        });
        Webcam.attach('#my_camera');
    }

    close.onclick = function() {
        modal.style.display = "none";
        Webcam.reset();
    }

    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }



    

    function showError(error) {
        if (error.code === 1) {
            data.innerHTML = "User denied the request for Geolocation.";
        }
        else if (err.code === 2) {
            data.innerHTML = "Location information is unavailable.";
        }
        else if (err.code === 3) {
            data.innerHTML = "The request to get user location timed out.";
        }
        else {
            data.innerHTML = "An unknown error occurred.";
        }
    }
</script>

</body>

Project/ITSSelfRunning/Views/Run/StartTraining.cshtml
@model Lib.Activity


@{
    ViewData["Title"] = "StartTraining";
}

<h2>StartTraining</h2>

<div>
    <div class="row">
        <h4>Name: @Model.Name</h4>
    </div>
    <div class="row">
        <h4>Place: @Model.Place</h4>
    </div>
</div>



<div class="row">
    @Html.ActionLink("Run Training", "RunTraining", new { activityId = Model.Id, isToOpen = true, activityType = Model.Type, uriGara = Model.UriGara}, new { @class = "btn btn-primary btn-large" })
</div>

Project/ITSSelfRunning/Views/Run/ViewTrainingData.cshtml
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAh4cgxhziWIt6rEa5XFffeOmEBmMIEesA&libraries=geometry"></script>

@{Html.RenderPartial("ActivityData", ViewData["Activity"]);}
@{Html.RenderPartial("PointData", ViewData["Telemetry"]);}