Project/SharedRuns/Models/RaceViewModels/RaceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SharedRuns.Models.RaceViewModels
{
    public class RaceViewModel
    {
        public string Name { get; set; }
        public string IdOrganizer { get; set; }
        public string Place { get; set; }
        public DateTime CreationDate { get; set; }
        public string UriGara { get; set; }
    }
}

Project/SharedRuns/Controllers/RaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LibSharedRun;
using LibSharedRun.Repos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SharedRuns.Models;
using SharedRuns.Models.RaceViewModels;

namespace SharedRuns.Controllers
{
    public class RaceController : Controller
    {

        private readonly IActivityRepo _activityRepo;
        private readonly UserManager<ApplicationUser> _userManager;

        public RaceController(IActivityRepo activityRepo, UserManager<ApplicationUser> userManager)
        {
            _activityRepo = activityRepo;
            _userManager = userManager;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _activityRepo.GetAllRacesAsync());
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(RaceViewModel raceVM)
        {
            if (ModelState.IsValid)
            {
                Activity act = new Activity
                {
                    Name = raceVM.Name,
                    Place = raceVM.Place,
                    Type = 2, //1= training, 2 = gara
                    CreationDate = DateTime.Now,
                    IdOrganizer = _userManager.GetUserId(User),
                    UriGara = raceVM.UriGara
                };
                await _activityRepo.InsertAsync(act);
            }

            return RedirectToAction("Index");
        }



        [Authorize]
        public async Task<IActionResult> Details(string uriGara)
        {
            Activity act = await _activityRepo.GetRaceDetailsAsync(uriGara);
            RaceViewModel rvm = new RaceViewModel()
            {
                Place = act.Place,
                CreationDate = act.CreationDate,
                Name = act.Name,
                UriGara = act.UriGara,
                IdOrganizer = act.IdOrganizer
            };
            return View(rvm);
        }
    }
}

Project/SharedRuns/Views/Race/Create.cshtml
@model SharedRuns.Models.RaceViewModels.RaceViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>RaceViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Place" class="control-label"></label>
                <input asp-for="Place" class="form-control" />
                <span asp-validation-for="Place" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UriGara" class="control-label"></label>
                <input asp-for="UriGara" class="form-control" />
                <span asp-validation-for="UriGara" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Project/SharedRuns/Views/Race/Details.cshtml
@model SharedRuns.Models.RaceViewModels.RaceViewModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>RaceViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdOrganizer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdOrganizer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Place)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Place)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UriGara)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UriGara)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Project/SharedRuns/Views/Race/Index.cshtml
@model IEnumerable<LibSharedRun.Activity>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-controller="Race" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Place)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreationDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UriGara)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Place)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UriGara)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new {  uriGara=item.UriGara })
            </td>
        </tr>
}
    </tbody>
</table>